<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\WebApplications\Microsoft.WebApplication.targets" Condition="Exists('$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\WebApplications\Microsoft.WebApplication.targets')" />
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <OutputType>Library</OutputType>
    <TargetFrameworkVersion>v4.8</TargetFrameworkVersion>
    <RootNamespace>KUETHardwareAccelerationClub</RootNamespace>
    <AssemblyName>KUETHardwareAccelerationClub</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="App_Start\RouteConfig.cs" />
    <Compile Include="Controllers\AccountController.cs" />
    <Compile Include="Controllers\HomeController.cs" />
    <Compile Include="Controllers\ProjectsController.cs" />
    <Compile Include="Controllers\TeamController.cs" />
    <Compile Include="Global.asax.cs">
      <DependentUpon>Global.asax</DependentUpon>
    </Compile>
    <Compile Include="Models\ClubModels.cs" />
    <Compile Include="Services\ClubRepository.cs" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Content\site.css" />
    <Content Include="Global.asax" />
    <Content Include="Views\**\*.cshtml" />
    <Content Include="Scripts\site.js" />
    <Content Include="Web.config" />
    <Content Include="Views\Web.config" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System" />
    <Reference Include="System.Configuration" />
    <Reference Include="System.Core" />
    <Reference Include="System.Web" />
    <Reference Include="System.Web.Mvc" />
    <Reference Include="System.Web.Razor" />
    <Reference Include="System.Web.WebPages" />
    <Reference Include="System.Web.WebPages.Razor" />
  </ItemGroup>
</Project>
